version: '2'
services:
  rendezveny-db:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: rendezveny-db
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=rendezveny
      - MYSQL_USER=rendezveny
      - MYSQL_PASSWORD=rendezveny
    networks:
      - rendezveny-db-network

  rendezveny-server:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: rendezveny-server
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DATABASE_HOST=rendezveny-db
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=rendezveny
      - DATABASE_PASSWORD=rendezveny
      - DATABASE_DATABASE=rendezveny
      - TOKEN_SECRET=rendezveny
      - SECURITY_DOMAIN=localhost:3000
      - DEBUG=1
    ports:
      - 3000:3000
    networks:
      - rendezveny-db-network
    depends_on:
      - rendezveny-db

  rendezveny-client:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
      args:
        GATSBY_SERVER_API_URL: http://localhost:3000/api/v1
    container_name: rendezveny-client
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GATSBY_SERVER_API_URL=http://localhost:3000/api/v1
    ports:
      - 9000:9000
    depends_on:
      - rendezveny-server

networks:
  rendezveny-db-network: